# Generated by Django 4.1.7 on 2023-03-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, max_length=33000, null=True),
        ),
    ]
