# Generated by Django 4.1.7 on 2023-03-07 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 3, 7, 0, 45, 32, 262005, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
