# Generated by Django 4.1.7 on 2023-03-07 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
