# Generated by Django 4.1.7 on 2023-03-07 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_friends_friendrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
